import '../styles/globals.css'
import {MoralisProvider} from "react-moralis"
import Header from "../components/Header"
import Head from 'next/head'

function MyApp({ Component, pageProps }) {
  return (
  <MoralisProvider appId="lgvq2FDr8YezFUkcMOneTyqWXIlOWBjGkgDv0KnZ" serverUrl="https://txjtfdgojmmf.usemoralis.com:2053/server">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       <Header/>
       <Component {...pageProps} />
  </MoralisProvider>
 
  )
}

export default MyApp
